name: flutter_learning
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  go_router: ^12.1.0
  flutter_bloc: ^9.1.1
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
