name: flutter_learning
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  go_router: ^16.0.0
  flutter_bloc: ^9.1.1
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  bloc: ^9.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/google.png
    - assets/icons/fb.png
    - assets/icons/apple.png
    - assets/images/pavlovvisuals.png
    - assets/images/profile_image.jpg
    - assets/images/profile_image2.jpg
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans/WorkSans-Bold.ttf
          weight: 700
